stages:
  - deploy

pages:
  stage: deploy
  image: node:22.13.0
  tags:
    - docker
  script:
    - node -v
    - npm ci
    - npm run build
    - mkdir -p public
    - cp -r dist/* public/
  artifacts:
    paths:
      - public
  only:
    - main
